<?php

namespace App\Connections\tests;



use App\Factories\ConnectionFactory;
use PDO;
use PHPUnit\Framework\TestCase;

class SQLiteConnectionTest extends TestCase
{
    private $conn;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->conn=ConnectionFactory::getSQLiteConnection();
    }

    private function dropTable($table){
        $sql=$this->conn->getConnection()->prepare("DROP TABLE ".$table);

        if($sql->execute()){
            echo " Table deleted. ";
        }else{
            print_r($sql->errorInfo());
        }
    }

    public function testCreateTable()
    {

        $this->conn->createTable('kicia', ['kako', 'mako']);

        $rawConn = $this->conn->getConnection();
        $sql = "SELECT  `name` FROM sqlite_master WHERE `type`='table'  ORDER BY name";
        $result = $rawConn->query($sql);
        $kicia=false;
        if ($result) {
            while ($row = $result->fetch(PDO::FETCH_ASSOC)) {
               if( $row['name'] = 'kicia');
               $kicia=true;
            }
        }
        self::assertTrue($kicia);
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        $this->dropTable('kicia');
    }
}


?>


}
}
